// <auto-generated />
namespace Imobiliaria2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AdicionandoSituacaoPropriedade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdicionandoSituacaoPropriedade));
        
        string IMigrationMetadata.Id
        {
            get { return "201706281227075_AdicionandoSituacaoPropriedade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
